version: '3.1'

services:
  api:
    build: ./api
    restart: always
    container_name: realtime-chat
    environment:
      PORT: 8443
      JWT_SECRET: chavedev
      MONGO_URL: mongodb+srv://arthur2228:EXMHczye9Fxw3z9F@pessoal.svpyb.mongodb.net/simple-chat?retryWrites=true&w=majority
    ports:  
      - "8443:8443"

  web:
    build: ./web
    restart: always
    container_name: web-realtime 
    ports:
      - "80:3000"
