version: '3.1'
services:
  api:
    build: ./api
    restart: always
    container_name: realtime-chat
    environment:
      PORT: 8433
      JWT_SECRET: chavedev
      MONGO_URL_DEV: mongodb+srv://arthur2228:EXMHczye9Fxw3z9F@pessoal.svpyb.mongodb.net/simple-chat?retryWrites=true&w=majority
    ports:  
      - "8433:8433"
    secrets:
    - certs
secrets:
  certs:
    file: ./agent2-k.pem
    file: ./agent2-c.pem
  web:
    build: ./web
    restart: always
    container_name: web-realtime 
    ports:
      - "80:3000"
    
