version: '3.1'
services:
  api:
    build: ./api
    restart: always
    container_name: realtime-chat
    environment:
      PORT: 7000
      JWT_SECRET: chavedev
      MONGO_URL_DEV: mongodb+srv://arthur2228:EXMHczye9Fxw3z9F@pessoal.svpyb.mongodb.net/simple-chat?retryWrites=true&w=majority
    ports:  
      - "80:7000"
  web:
    build: ./web
    restart: always
    container_name: realtime-chat-web
    ports:
      - "3000:3000"
    
