# Use root/example as user/password credentials
version: '3.1'
services:
  api:
    environment:
      PORT: 8080
      JWT_SECRET: chaveprod
      MONGO_URL_DEV: mongodb://root:example@mongo:27017
    image: arthursantos2228/realtime-chat
    restart: always

