version: '3.1'
services:
  api:
    build: ./api
    restart: always
    container_name: realtime-chat
    environment:
      PORT: 7000
      JWT_SECRET: chavedev
      MONGO_URL_DEV: mongodb://root:example@mongo:27017
    ports:  
      - "80:7000"
  web:
    build: ./web
    restart: always
    container_name: realtime-chat-web
    ports:
      - "3000:3000"
    
