version: '3.1'
services:
  api:
    build: ./api
    restart: always
    container_name: realtime-chat
    environment:
      PORT: 8080
      JWT_SECRET: chaveprod
      MONGO_URL: mongodb+srv://arthur2228:EXMHczye9Fxw3z9F@pessoal.svpyb.mongodb.net/simple-chat?retryWrites=true&w=majority
      MONGO_URL_DEV: mongodb://root:example@mongo:27017
    ports:  
      - "8080:8080"
  web:
    build: ./web-interface
    restart: always
    container_name: realtime-chat-web
    ports:
      - "3000:3000"
    
