version: '3.1'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  api:
    build: .
    restart: always
    container_name: realtime-chat-dev
    environment:
      PORT: 8080
      JWT_SECRET: devkey
      MONGO_URL_DEV: mongodb://root:example@localhost:27017/
    ports: 
      - "80:8080"