name: Realtime chat CI/CD
on:  
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:

  upload-docker-container-app-to-remote-repo:
    name: CI
    runs-on: ubuntu-latest
    environment:
      name: main
        
    steps:
    - uses: actions/checkout@v2
    - name: logout
      run: docker logout 
    
    - name: Build The Docker api Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest

    - name: Build The Docker web Image
      run: docker build ./web --tag arthursantos2228/web-realtime:latest

    - name: docker login 
      env:
        USER_SECURE: ${{secrets.USER_SECRET}}
        PASSWORD_SECURE: ${{secrets.PASS_SECRET}}
      run: |
        docker login -u $USER_SECURE -p $PASSWORD_SECURE 

    - name: Docker push api
      run: docker push arthursantos2228/realtime-chat:latest

    - name: Docker push web
      run: docker push arthursantos2228/web-realtime:latest

  docker-container-back:
    name: CD-back
    runs-on: ubuntu-latest
    environment:
      name: deployprod
      url: 'https://service.arthursantos.tech:8443/messages'
    needs: upload-docker-container-app-to-remote-repo

    steps:
    - name: deploy back with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST_ROSE}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: ${{secrets.PORT}}
        passphrase: ${{secrets.PASSWORD}} 
        debug: true
        script: |
          sudo docker container rm realtime-chat -f \
          && sudo docker image rm arthursantos2228/realtime-chat -f \
          && sudo docker-compose up -d
    
  docker-container-front:
    name: CD-front
    runs-on: ubuntu-latest
    environment:
      name: deployprod
      url: 'https://www.arthursantos.tech/'
    needs: upload-docker-container-app-to-remote-repo

    steps:
    - name: deploy front with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST_MARIA}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: ${{secrets.PORT}}
        passphrase: ${{secrets.PASSWORD}} 
        debug: true
        script: |
          sudo docker container rm web-realtime -f \
          && sudo docker image rm arthursantos2228/web-realtime -f \
          && sudo docker-compose up -d
    
