name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: logout
      run: docker logout 
    
    - name: Build The Docker Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest 

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD" docker.io
    
    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

