name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
      env:
        USER: ${{secrets.DOCKER_USER}}
        PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: logout
      run: docker logout 
    
    - name: Build The Docker Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest

    - name: t2
      run: echo ${{env.USER}} ${{env.PASSWORD}}
    
    - name: t3
      run: echo $USER $PASSWORD

    - name: t4
      run: echo "$USER" "$PASSWORD"

    - name: docker login 
      run: docker login -u ${{env.USER}} -p ${{env.PASSWORD}}

    
    
    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

