name: Realtime chat CI/CD
on:  
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:

  # build:
  #   name: CI
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: main
        
  #   steps:
  #   - uses: actions/checkout@v2

  #   - name: logout
  #     run: docker logout 
    
  #   - name: Build The Docker Image
  #     run: docker build ./api --tag arthursantos2228/realtime-chat:latest

  #   - name: docker login 
  #     env:
  #       USER_SECURE: ${{secrets.USER_SECRET}}
  #       PASSWORD_SECURE: ${{secrets.PASS_SECRET}}
  #     run: |
  #       docker login -u $USER_SECURE -p $PASSWORD_SECURE 

  #   - name: Docker push 
  #     run: docker push arthursantos2228/realtime-chat:latest

  deploy-prod:
    name: CD
    runs-on: ubuntu-latest
    environment:
      name: deployprod
      url: 'http://13.66.205.253/messages'
    # needs: build

    steps:
    - name: deploy with ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.HOST}}
        username: ${{secrets.USERNAME}}
        key: ${{secrets.PRIVATE_KEY}}
        port: ${{secrets.PORT}}
        passphrase: ${{secrets.PASSWORD}}
        script: pwd \ 
          docker-compose -f home/acs/docker-compose.yml up -d 
