name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build The Docker Image
      run: docker build ./api --file Dockerfile --tag arthursantos2228/realtime-chat:latest
    
    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

