name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u arthursantos2228 -p Acs2228@tt7
    
    - name: Build The Docker Image
      run: docker build ./api --file Dockerfile --tag arthursantos2228/realtime-chat:latest
    
    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

