name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

      # env:
      #   USER: ${{secrets.DOCKER_USER}}
      #   PASSWORD: ${{secrets.DOCKER_PASSWORD}}

    - name: logout
      run: docker logout 
    
    - name: Build The Docker Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest

    - name: docker login 
      run: |
        docker login -u $USER_SECURE -p $PASSWORD_SECURE docker.io
      env:
        USER_SECURE: ${{ secrets.USERNAME_ID }}
        PASSWORD_SECURE: ${{ secrets.PASSWORD_VALUE }}

    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

