name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: logout
      run: docker logout 
    
    - name: Build The Docker Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest

    - name: docker login 
      env:
        USER_SECURE: ${{secrets.USERNAME_ID}}
        PASSWORD_SECURE: ${{secrets.PASSWORD_VALUE}}
      run: |
        docker login -u $USER_SECURE -p $PASSWORD_SECURE 

    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

