name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: logout
      run: docker logout 
    
    - name: Build The Docker Image
      run: docker build ./api --tag arthursantos2228/realtime-chat:latest

    - name: Test printing your secret (Remove this step in production)
      run: cat $HOME/secrets/main.json

    - name: docker login 
      env:
        USER_SECURE: ${{secrets.USER_SECRET}}
        PASSWORD_SECURE: ${{secrets.PASS_SECRET}}
      run: |
        docker login -u $USER_SECURE -p $PASSWORD_SECURE 


    - name: Docker push 
      run: docker push arthursantos2228/realtime-chat:latest

   
